apache/incubator-hugegraph-toolchain

src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/LoaderTest.java

Improve #9
Change-Id: Idafceec6abc3b0feed0027c1b4e3b43dbe7ca166

Support load data with set cardinality property

---

assembly/static/example/struct.json
assembly/static/example/vertex_software.text
src/main/java/com/baidu/hugegraph/loader/parser/ElementParser.java
src/main/java/com/baidu/hugegraph/loader/serializer/EdgeSourceDeserializer.java
src/main/java/com/baidu/hugegraph/loader/serializer/VertexSourceDeserializer.java
src/main/java/com/baidu/hugegraph/loader/source/EdgeSource.java
src/main/java/com/baidu/hugegraph/loader/source/ElementSource.java
src/main/java/com/baidu/hugegraph/loader/source/VertexSource.java

implement: #1
Change-Id: I915bb5e0dfc35c57a902b1d440fe4dcde65ec683

add ignore mechanism to data source JSON config file

---

src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
src/main/java/com/baidu/hugegraph/loader/reader/file/FileReader.java

Fix #15
Change-Id: Id90b08508a2f43508f7099650795f0b844e317e2

Improve exception message about check file

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/parser/EdgeParser.java
src/main/java/com/baidu/hugegraph/loader/parser/ElementParser.java
src/main/java/com/baidu/hugegraph/loader/parser/VertexParser.java
src/test/java/com/baidu/hugegraph/loader/test/functional/LoaderTest.java
src/test/resources/schema_joint_pk.groovy
src/test/resources/struct_joint_pk.json

Fix #17
Change-Id: I74ff2445602ff8afb76b58c3e9da5ea68eebeb27

Fix bug vertices has joint primary keys load error

---

src/main/java/com/baidu/hugegraph/loader/parser/EdgeParser.java
src/main/java/com/baidu/hugegraph/loader/parser/ElementParser.java
src/main/java/com/baidu/hugegraph/loader/parser/VertexParser.java
src/test/java/com/baidu/hugegraph/loader/test/functional/LoaderTest.java
src/test/resources/schema_number_id.groovy
src/test/resources/struct_number_id.json

Change-Id: If53feef102ecd66b78dc0f2ac2f83c4664b20a29

Fix edge parser error check property key when customized id

---

src/main/java/com/baidu/hugegraph/loader/reader/file/FileReader.java
src/main/java/com/baidu/hugegraph/loader/source/file/FileSource.java
src/test/java/com/baidu/hugegraph/loader/test/functional/LoaderTest.java
src/test/resources/struct_comment_symbol.json

Change-Id: Id5a664a3d0c09bac7cb3761862ab69bfd8cca5dd

Support to skip the line start with specified symbols

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/exception/ReadException.java
src/main/java/com/baidu/hugegraph/loader/reader/file/FileReader.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/LoaderTest.java
src/test/resources/struct_vertex_dir.json

Implement #29
Change-Id: Id3d9385b52484a30d6e71652ef1b55c40979dd88

Support load with a specified directory

---

assembly/static/example/edge_created.json
assembly/static/example/schema.groovy
assembly/static/example/struct.json
pom.xml
src/main/java/com/baidu/hugegraph/loader/parser/EdgeParser.java
src/main/java/com/baidu/hugegraph/loader/parser/ElementParser.java
src/main/java/com/baidu/hugegraph/loader/parser/VertexParser.java
src/main/java/com/baidu/hugegraph/loader/source/file/FileSource.java
src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java
src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
src/main/java/com/baidu/hugegraph/loader/util/DateUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/LoaderTest.java
src/test/resources/schema_date_format.groovy
src/test/resources/struct_date_format.json

Implement #27
Change-Id: Ib00a1b6d53dee82c7be7cb8420662787707161d5

Support customized date format

---

src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java

fixed: #37
Change-Id: Ieafb22a7805ecb834a7d412a770b115c6bbd98f9

improve url regex regex

---

assembly/static/example/file/struct.json
assembly/static/example/hdfs/struct.json
src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
src/main/java/com/baidu/hugegraph/loader/util/HugeClientWrapper.java

Change-Id: Id2d748f83ce3c52dc961ba32b044dff6e40b6615

Add an option 'token' for authentication

---

pom.xml

Change-Id: Iaebd63883e0878c0c1a822e8e4f9a6bf466c2b5d

Upgrade and temporarily comment vulnerable dependency

---

pom.xml

Change-Id: Iee025b4e6700bd61936f5ccea9a02608c1fb8c83

Upgrade version to 0.9.0

---

src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/mapping_ignore_null_value_columns/schema.groovy
src/test/resources/mapping_ignore_null_value_columns/struct.json

Change-Id: I87d47ef14334a8326ce96e4def4571a0ed31e5fd
Fix #63

Fix nullable key in mapping field can't work

---

src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
src/main/java/com/baidu/hugegraph/loader/util/HugeClientWrapper.java

Allow users to modify the connection pool options while modifying the number of loader's threads

Add http-connection options

---

src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/executor/LoadSummary.java
src/main/java/com/baidu/hugegraph/loader/util/LoaderUtil.java

1. add parserSuccess to comfirm data integrity
2. add parserSpeed to get performance results directly
3. record the import speed of each data source in the log for comparison

Enhance summary info

---

.gitignore
src/main/java/com/baidu/hugegraph/loader/reader/file/FileReader.java
src/main/java/com/baidu/hugegraph/loader/reader/hdfs/HDFSReader.java
src/main/java/com/baidu/hugegraph/loader/source/file/FileFilter.java
src/main/java/com/baidu/hugegraph/loader/source/file/FileSource.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/filter_file_by_suffix/schema.groovy
src/test/resources/filter_file_by_suffix/struct.json
src/test/resources/filter_path_by_suffix/schema.groovy
src/test/resources/filter_path_by_suffix/struct.json

Implement #44
Change-Id: I25484c390015daacd907ea102c31c1f8aaa8f495

Support filter files by file name suffix

---

.travis.yml
pom.xml
src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/progress/InputProgress.java
src/main/java/com/baidu/hugegraph/loader/progress/LoadProgress.java
src/main/java/com/baidu/hugegraph/loader/summary/LoadSummary.java
src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java
src/main/java/com/baidu/hugegraph/loader/util/Printer.java
src/test/java/com/baidu/hugegraph/loader/test/unit/LoadProgressTest.java
src/test/java/com/baidu/hugegraph/loader/test/unit/UnitTestSuite.java

Change-Id: I112261828af7267ba7463461153486af3ea97d4f

Fix acquired semaphores num error when wait task finished

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/reader/jdbc/JDBCReader.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/java/com/baidu/hugegraph/loader/test/functional/JDBCLoadTest.java
src/test/resources/empty_file_with_header/schema.groovy
src/test/resources/empty_file_with_header/struct.json
src/test/resources/empty_file_without_header/schema.groovy
src/test/resources/empty_file_without_header/struct.json

Change-Id: I6449b93a23c01ed804c71c650d9f8712b26a1af7

Fix empty table hasNext return true

---

src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/customized_long_id/schema.groovy
src/test/resources/customized_long_id/struct.json
src/test/resources/long_property/schema.groovy
src/test/resources/long_property/struct.json

Change-Id: Iae2aa1e6d4f1b765d902fda6613d6143b3590f69

Support unsigned long property

---

src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/builder/SchemaCache.java
src/main/java/com/baidu/hugegraph/loader/constant/Constants.java
src/main/java/com/baidu/hugegraph/loader/parser/CsvLineParser.java
src/main/java/com/baidu/hugegraph/loader/parser/TextLineParser.java
src/main/java/com/baidu/hugegraph/loader/progress/LoadProgress.java
src/main/java/com/baidu/hugegraph/loader/reader/Line.java
src/main/java/com/baidu/hugegraph/loader/reader/file/FileReader.java
src/main/java/com/baidu/hugegraph/loader/reader/file/Readers.java
src/main/java/com/baidu/hugegraph/loader/reader/hdfs/HDFSFileReader.java
src/main/java/com/baidu/hugegraph/loader/reader/jdbc/RowFetcher.java
src/main/java/com/baidu/hugegraph/loader/source/file/FileSource.java
src/main/java/com/baidu/hugegraph/loader/source/file/SkippedLine.java
src/main/java/com/baidu/hugegraph/loader/source/jdbc/JDBCVendor.java
src/main/java/com/baidu/hugegraph/loader/struct/ElementStruct.java
src/main/java/com/baidu/hugegraph/loader/task/BatchInsertTask.java
src/main/java/com/baidu/hugegraph/loader/task/SingleInsertTask.java
src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
src/main/java/com/baidu/hugegraph/loader/util/HugeClientHolder.java
src/test/java/com/baidu/hugegraph/loader/test/functional/DBUtil.java

Change-Id: Ic7addbf75b324c931aeeca7f244e993547d136d1

Improve some code

---

assembly/static/example/file/struct.json
assembly/static/example/hdfs/struct.json
pom.xml
src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
src/main/java/com/baidu/hugegraph/loader/builder/VertexBuilder.java
src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/java/com/baidu/hugegraph/loader/test/functional/LoadTest.java
src/test/resources/customized_uuid/schema.groovy
src/test/resources/customized_uuid/struct.json
src/test/resources/value_uuid_property_in_file/schema.groovy

Change-Id: If7bd8a59eccf4cfb6d138a7acba1923f912dbc2c

Support uuid idstrategy

---

src/main/java/com/baidu/hugegraph/loader/struct/ElementStruct.java
src/main/java/com/baidu/hugegraph/loader/task/BatchInsertTask.java
src/main/java/com/baidu/hugegraph/loader/task/InsertTask.java
src/main/java/com/baidu/hugegraph/loader/task/SingleInsertTask.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileUtil.java
src/test/resources/update_by_strategy/invalid_strategy_struct.json
src/test/resources/update_by_strategy/schema.groovy
src/test/resources/update_by_strategy/struct.json

The strategy in JSON is case sensitive now, wait for jackthon update to V2.9+ to support case-insensitive original

Support batch update element properties with strategies

---

src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/update_by_strategy_without_symbol/no_list_format_struct.json
src/test/resources/update_by_strategy_without_symbol/schema.groovy
src/test/resources/update_by_strategy_without_symbol/struct.json

Change-Id: Ia4d307776b86c6bcbe2b06957b4cf4cb921d9c3d

Fix list or set property update failed

---

src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/struct/ElementStruct.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/skip_struct/schema.groovy
src/test/resources/skip_struct/struct.json

implement #100
Change-Id: Ie7fb4a11e17e957b111dddb972845f444a5e8053

Support skip struct to avoid delete it

---

pom.xml

Change-Id: If74cc9fd3e9cf132b3c4fc3f9ff0c135d3077634

Upgrade version to 0.10.0

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/task/BatchInsertTask.java
src/main/java/com/baidu/hugegraph/loader/task/InsertTask.java
src/main/java/com/baidu/hugegraph/loader/task/SingleInsertTask.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/single_insert_edge_with_check_vertex_false/schema.groovy
src/test/resources/single_insert_edge_with_check_vertex_false/struct.json
src/test/resources/single_insert_edge_with_check_vertex_false/struct_hdfs.json

Change-Id: Id559e0d1e5ce4dc6f54b68646e1883a4fa6fb9e9

Let single edge insert support options.checkVertex

---

src/main/java/com/baidu/hugegraph/loader/exception/InsertException.java
src/main/java/com/baidu/hugegraph/loader/exception/ParseException.java
src/main/java/com/baidu/hugegraph/loader/task/SingleInsertTask.java

Change-Id: I947c86b38f2aaf1736dc66b1a6a303ad234aa21a

Let print insert error just once time to avoid too much output

---

src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/java/com/baidu/hugegraph/loader/test/functional/HDFSLoadTest.java
src/test/java/com/baidu/hugegraph/loader/test/functional/JDBCLoadTest.java

Change-Id: Ib00182949aa3ce74a5c7170f537e8463b03d0d7e

Split num threads for batch and single insert

---

assembly/static/bin/utf8-bom-to-utf8.sh

Change-Id: If9bbcfdba9a78b28a5034c17916ab2eacefb2345

Add an shell tool used to convert utf8-bom to utf8

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/parser/CsvLineParser.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/parse_empty_csv_line/schema.groovy
src/test/resources/parse_empty_csv_line/struct.json
src/test/resources/parse_empty_csv_line/struct_hdfs.json

Change-Id: I852f8438a5d9d1e7a31a4bf9f36366d13923ba4a

Use SimpleFlatMapper csv parser

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
src/main/java/com/baidu/hugegraph/loader/util/JsonUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/number_and_date_pks_encoded/schema.groovy
src/test/resources/number_and_date_pks_encoded/struct.json
src/test/resources/number_and_date_pks_encoded/struct_hdfs.json

Fix https://github.com/hugegraph/hugegraph/issues/852
Change-Id: I797963f9977cf8bdde81037b29e79ba81e566c93

Encoded number and date primary values

---

src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/source_or_target_pk_value_null/schema.groovy
src/test/resources/source_or_target_pk_value_null/struct.json
src/test/resources/source_or_target_pk_value_null/struct_hdfs.json
src/test/resources/vertex_pk_value_null/schema.groovy
src/test/resources/vertex_pk_value_null/struct.json
src/test/resources/vertex_pk_value_null/struct_hdfs.json

Change-Id: I7bd1cc6c6333032b0ba1f2460a6fe25696fab420

Ensure primary key columns valid or participate field mapping

---

src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/id_field_as_property/schema.groovy
src/test/resources/id_field_as_property/struct.json
src/test/resources/id_field_as_property/struct_hdfs.json

Fix #133
Change-Id: I6f91c8073029d430a934e68f69f3167b182720f7

Support id field stored as property

---

src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
src/main/java/com/baidu/hugegraph/loader/util/HugeClientHolder.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/java/com/baidu/hugegraph/loader/test/functional/LoadTest.java
src/test/resources/clear_schema_before_load/schema.groovy
src/test/resources/clear_schema_before_load/struct.json
src/test/resources/clear_schema_before_load/struct_hdfs.json

Fix #134
Change-Id: Icc8c096e6c1539370ccfcd83b4a9753ab03040b1

Support to clear schema before loading

---

src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
src/main/java/com/baidu/hugegraph/loader/util/HugeClientHolder.java

Change-Id: I609a6e6b3be366d8ee5953879004d85fb2c33ab9

Support config username in load options

---

assembly/static/conf/log4j2.xml
pom.xml
src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
src/main/java/com/baidu/hugegraph/loader/executor/LoadContext.java
src/main/java/com/baidu/hugegraph/loader/mapping/ElementMapping.java
src/main/java/com/baidu/hugegraph/loader/mapping/InputStruct.java
src/main/java/com/baidu/hugegraph/loader/metrics/LoadSummary.java
src/main/java/com/baidu/hugegraph/loader/reader/hdfs/HDFSFileReader.java
src/main/java/com/baidu/hugegraph/loader/util/JsonUtil.java
src/main/java/com/baidu/hugegraph/loader/util/LoadUtil.java
src/main/java/com/baidu/hugegraph/loader/util/Printer.java
src/main/resources/log4j2.xml
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/HDFSUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/IOUtil.java
src/test/resources/parquet_compress_file/core-site.xml
src/test/resources/parquet_compress_file/struct_hdfs.json

Change-Id: Id6a75b45cd00f9e9285bcd54ecf50342d0dafe69

Some improve for adapting hubble

---

src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
src/main/java/com/baidu/hugegraph/loader/metrics/LoadSummary.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/read_reached_max_lines/schema.groovy
src/test/resources/read_reached_max_lines/struct.json
src/test/resources/read_reached_max_lines/struct_hdfs.json

Change-Id: I2b74b32e0693773ca0fa36505bb26fc98e82ea0f

Support specify the max read lines

---

src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
src/main/java/com/baidu/hugegraph/loader/mapping/ElementMapping.java
src/main/java/com/baidu/hugegraph/loader/task/BatchInsertTask.java
src/main/java/com/baidu/hugegraph/loader/task/InsertTask.java
src/main/java/com/baidu/hugegraph/loader/task/SingleInsertTask.java
src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java

Change-Id: I9bd2254629b0bab3a7dfc2622c7435fd8f1b30f5

Some small optimization

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/builder/SchemaCache.java
src/main/java/com/baidu/hugegraph/loader/constant/Constants.java
src/main/java/com/baidu/hugegraph/loader/executor/LoadContext.java
src/main/java/com/baidu/hugegraph/loader/mapping/ElementMapping.java
src/main/java/com/baidu/hugegraph/loader/struct/ElementStructV1.java
src/main/java/com/baidu/hugegraph/loader/task/BatchInsertTask.java
src/main/java/com/baidu/hugegraph/loader/task/InsertTask.java
src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
src/main/java/com/baidu/hugegraph/loader/util/HugeClientHolder.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/java/com/baidu/hugegraph/loader/test/functional/LoadTest.java
src/test/resources/orc_compress_file/struct.json
src/test/resources/timestamp_as_dateformat/schema.groovy
src/test/resources/timestamp_as_dateformat/struct.json
src/test/resources/timestamp_as_dateformat/struct_hdfs.json

Change-Id: I1b100b52f762046e3bdfa2c1df44b66a223758b3

Support timestamp as date format

---

src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
src/test/resources/source_or_target_pk_value_empty/schema.groovy
src/test/resources/source_or_target_pk_value_empty/struct.json
src/test/resources/source_or_target_pk_value_empty/struct_hdfs.json
src/test/resources/vertex_pk_value_empty/schema.groovy
src/test/resources/vertex_pk_value_empty/struct.json
src/test/resources/vertex_pk_value_empty/struct_hdfs.json

Implement #165
Change-Id: Ie9e1cc1f4141f9f63f57734faf36caefacef9691

Skip vertex whose primary values are all empty

---

src/test/resources/source_or_target_pk_value_empty/struct_hdfs.json

Change-Id: I971c18bd766c84b328d6d8e62fb96bbfb9b944e5

Modify struct_hdfs.json in testSourceOrTargetPrimaryValueEmpty

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/executor/LoadContext.java
src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java

Change-Id: Ic8edcea08178db295313c9c40e173a0e6438c6e8

Set loading mode before load and reset after load

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/executor/LoadContext.java
src/main/java/com/baidu/hugegraph/loader/task/ParseTaskBuilder.java
src/main/java/com/baidu/hugegraph/loader/task/SingleInsertTask.java
src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java
src/main/java/com/baidu/hugegraph/loader/util/Printer.java

Change-Id: I78ab4e61b51641717ab02b240077803840bc1650

Some improve for stopping load

---

pom.xml

Change-Id: I8c828790dfe910b8c683170c128db682fce797e6

Upgrade to version 0.11.0 for release

---

src/main/java/com/baidu/hugegraph/loader/reader/file/LocalFileReader.java
src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
src/main/java/com/baidu/hugegraph/loader/reader/hdfs/HDFSFileReader.java
src/main/java/com/baidu/hugegraph/loader/util/ParquetUtil.java

1、Read parquet file by path
2、Adapt INT96 etc. DataType
3、Support enable kerberos authentication

Read parquet file by path&Adapt INT96 etc. DataType

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/constant/Constants.java
src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
src/main/java/com/baidu/hugegraph/loader/util/HugeClientHolder.java

fix #185
Change-Id: Ib99a3d408b53699c892f1bb2baa664add0ed3eef

Fix bugs about jdbc url slash and trust store file path 

---

src/main/java/com/baidu/hugegraph/loader/executor/LoadContext.java
src/main/java/com/baidu/hugegraph/loader/failure/FailLogger.java

Change-Id: Ic7d1e0880274339f653feabae68c5b6ccc4ebf7d

Wrap exception when unset loading mode

---

pom.xml

Change-Id: Iadbaa5f6610c8f2dd2ae420a10f09856d7c0dc0a

Fix senstive mail address

---

pom.xml
src/main/java/com/baidu/hugegraph/loader/constant/Constants.java
src/main/java/com/baidu/hugegraph/loader/metrics/LoadSummary.java
src/main/java/com/baidu/hugegraph/loader/util/Printer.java

Change-Id: I6dfa9f527cfdc5c7175fe812ab24a129eb2d9df5

Fix read time maybe negitive

---

.github/workflows/ci.yml
pom.xml
src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
src/main/java/com/baidu/hugegraph/loader/metrics/LoadMetrics.java
src/main/java/com/baidu/hugegraph/loader/reader/file/FileReader.java
src/main/resources/log4j2.xml

Change-Id: I7002cee67f923191d6178e089aa848120a6d8e10

Improve log info for files under dir

---

.github/workflows/cla.yml

current pr replace and solve the cla robot can't merge problem
**Note:** we keep cla-assist as the store file branch now, keep it in future

chore: use cla assistant to support robot pr

---

hugegraph-hubble/hubble-be/pom.xml
hugegraph-loader/pom.xml
hugegraph-tools/pom.xml

add license-maven-plugin
implement [#1632](https://github.com/hugegraph/hugegraph/issues/1632)

add license-maven-plugin

---

hugegraph-tools/pom.xml

chore: fix hugegraph-tools Ant BuildException 

---

hugegraph-hubble/hubble-dist/assembly/travis/install-hugegraph-hubble.sh
hugegraph-hubble/hubble-dist/pom.xml
hugegraph-hubble/pom.xml
hugegraph-tools/pom.xml

chore: fix hubble-dist pacakge error & hubble-ci 

---

hugegraph-dist/pom.xml

chore: fix hugegraph-dist package error

---

hugegraph-loader/assembly/static/bin/get-params.sh
hugegraph-loader/assembly/static/bin/hugegraph-flinkcdc-loader.sh
hugegraph-loader/assembly/static/bin/hugegraph-spark-loader.sh

closed #317 
original submit command
```
${HG_LOADER_HOME}/bin/hugegraph-spark-loader.sh 
--master yarn  \
--deploy-mode cluster  \
--name test  \
--file /home/hive/huge.json  \
--username admin  \
--token xxx \
--host xxx \
--port xxx \
--graph xxx
```
- when option` --deploy-mode` equals `cluster`
```
engine_params:  --master yarn --deploy-mode cluster --name test --files /home/hive/huge.json
hugegraph_params:  --username admin --token xxx --host xxx --port xxx --graph xxx --file huge.json
```
- when option` --deploy-mode` equals `client`
```
engine_params:  --master yarn --deploy-mode client --name test
hugegraph_params:  --username admin --token xxx --host xxx --port xxx --graph xxx --file /home/hive/huge.json
```

feat: support yarn-cluster mode for spark-loader

---

hugegraph-client/assembly/travis/install-hugegraph-from-source.sh

temp code for troubleshooting

---

.github/workflows/client-ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/hubble-ci.yml
.github/workflows/loader-ci.yml
.github/workflows/tools-ci.yml

We need enable ci with all branches for devs to test

chore: improve ci configs for PRs

---

hugegraph-hubble/hubble-dist/pom.xml

fix parent artifactId env

---

hugegraph-dist/scripts/dependency/known-dependencies.txt
hugegraph-loader/pom.xml

fix loading data & computer CI error
TODO: we need add a test covered these case & throw the exception

chore: fix loader's jackson conflicts & missing dependencies

---

hugegraph-client/src/main/java/org/apache/hugegraph/serializer/direct/reuse/BytesDemo.java
hugegraph-hubble/hubble-be/src/main/java/org/apache/hugegraph/config/TomcatServletConfig.java
hugegraph-hubble/package.json
hugegraph-loader/src/main/java/org/apache/hugegraph/loader/util/ParquetUtil.java

follow https://github.com/apache/incubator-hugegraph/issues/1632#issuecomment-1396655141
@wanganjuan could u please check/update the hubble's json file? (remove it if we don't need)

chore(license): fix 3rd party license problems

---

hugegraph-dist/pom.xml

use the right file path for binary

chore: update LICENSE & NOTICE file path for binary package

---

.asf.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/license-checker.yml

use node.js version 16 to fixed ci problem

use node.js version 16 to fixed ci problem

---

.github/workflows/hubble-ci.yml
README.md
hugegraph-hubble/Dockerfile
hugegraph-hubble/README.md
hugegraph-hubble/hubble-dist/assembly/static/bin/start-hubble.sh

chore(hubble): use latest code in Dockerfile

---

hugegraph-hubble/hubble-dist/pom.xml

This plugin affects the build process for new docker image.

chore: remove maven plugin for docker build

---

README.md
hugegraph-client/README.md
hugegraph-loader/README.md
hugegraph-loader/src/main/java/org/apache/hugegraph/loader/spark/HugeGraphSparkLoader.java

doc: fix build status badge link

---

README.md

as title
SubTask of https://github.com/apache/incubator-hugegraph-doc/pull/218#pullrequestreview-1425795941

doc: add basic contact info & QR code in README

---

.asf.yaml

chore: disable PR up-to-date in branch

---

.asf.yaml

transfer pr status to issues mail to avoid a lot of mail forward

chore: update .asf.yaml for mail rule

---

README.md

doc: update reademe 

---

hugegraph-loader/assembly/static/example/spark/schema.groovy
hugegraph-loader/assembly/static/example/spark/struct-hbase.json
hugegraph-loader/assembly/static/example/spark/vertex_person.json
hugegraph-loader/assembly/static/example/spark/vertex_software.json

fix: Spark Loader example schema and struct mismatch

---

.github/PULL_REQUEST_TEMPLATE.md

copy from https://github.com/apache/incubator-hugegraph/blob/master/.github/PULL_REQUEST_TEMPLATE.md

feat: add pr template

---

.github/labeler.yml

chore(ci): add spark & go client module auto labeler

---

hugegraph-hubble/hubble-fe/src/components/graph-management/data-import/import-tasks/datamap-configs/EdgeMap.tsx
hugegraph-hubble/hubble-fe/src/components/graph-management/data-import/import-tasks/datamap-configs/VertexMap.tsx

Fixed an issue where the drop-down box could not display all options
- close #525
- xxx

fix(hubble): drop-down box could not display all options

---

hugegraph-dist/scripts/dependency/known-dependencies.txt
hugegraph-hubble/hubble-be/pom.xml

fix okhttp version

---

hugegraph-hubble/Dockerfile

- fix https://github.com/hugegraph/actions/actions/runs/7192571335/job/19589722823
- install node 16 with npm manually
- If we remove  `apt-get install -y npm`, then action throw the error `/bin/sh: 1: npm: not found` [error link](https://github.com/aroundabout/action_demo/actions/runs/7193598330/job/19592387256#step:6:6042) but if we `apt install npm` directly, the error is `Error: Cannot find module 'semver'` [error link](https://github.com/hugegraph/actions/actions/runs/7192571335/job/19589722823#step:7:12194). Hence I should install node 16 manually.
- There is also a question, we have installed node and yarn by plugin. Should we install npm in pom:
```xml
<execution>
<id>install node and yarn</id>
<goals>
<goal>install-node-and-yarn</goal>
</goals>
<configuration> …
```

fix: github action build hubble image failed

---

README.md
hugegraph-hubble/Dockerfile
hugegraph-hubble/README.md
hugegraph-hubble/hubble-dist/pom.xml
hugegraph-tools/src/main/java/org/apache/hugegraph/structure/JsonGraph.java
hugegraph-tools/src/main/java/org/apache/hugegraph/util/ToolUtil.java
hugegraph-tools/src/test/java/org/apache/hugegraph/test/functional/AuthBackupTest.java
hugegraph-tools/src/test/java/org/apache/hugegraph/test/functional/AuthRestoreTest.java
hugegraph-tools/src/test/java/org/apache/hugegraph/test/functional/CommandTest.java
hugegraph-tools/src/test/java/org/apache/hugegraph/test/util/FileUtil.java
pom.xml

- subtask of #543
- enhance #557 
- xxx

fix: build error with npm not exist & tiny improve

---

hugegraph-hubble/Dockerfile

- fix there are no curl in docker image of hubble-1.0.0
virified in my own dockerhub repo: https://hub.docker.com/repository/docker/dandelionivy/hubble/general
- xxx

chore(fix): docker image of hubble 1.0.0 have no curl

---

hugegraph-hubble/hubble-dist/pom.xml

- same issue: https://github.com/apache/incubator-hugegraph-toolchain/issues/520
- refer add timeout: https://github.com/apache/incubator-hugegraph-toolchain/pull/519
- xxx

fix(hubble): yarn install timeout in arm64

---

README.md
hugegraph-loader/README.md
pom.xml

- change rversion to 1.3.0  
- xxx

chore: upgrade version to 1.3.0

---

hugegraph-hubble/README.md

doc(hubble): enhance the README file

---

README.md

- close #xxx  
- add hyperlink to Apache 2.0 License in Readme documentation
- xxx

doc: update Readme style referring server's style

---

README.md
pom.xml

chore(dist): upgrade version to 1.5.0

---

hugegraph-loader/src/test/java/org/apache/hugegraph/loader/test/functional/DBUtil.java
hugegraph-loader/src/test/java/org/apache/hugegraph/loader/test/functional/JDBCLoadTest.java

- fix [#649](https://github.com/apache/incubator-hugegraph-toolchain/issues/649)
- xxx

refactor(loader): add a useSSL option for mysql

---

hugegraph-hubble/hubble-fe/src/i18n/resources/en-US/graph-managment/data-import/import-tasks/ImportTasks.json

Just fixing the "cancel" wording on some buttons.
- xxx

fix(hubble): typo word in display

---

hugegraph-client/src/main/java/org/apache/hugegraph/structure/constant/EdgeLabelType.java
hugegraph-client/src/main/java/org/apache/hugegraph/structure/schema/EdgeLabel.java
hugegraph-client/src/main/java/org/apache/hugegraph/structure/schema/VertexLabel.java
hugegraph-client/src/test/java/org/apache/hugegraph/api/EdgeLabelApiTest.java
hugegraph-loader/src/main/java/org/apache/hugegraph/loader/builder/EdgeBuilder.java

1. add a edge label type called `GENERAL`
2. add unit test for edge label type
- xxx

chore(client): patch for father sub edge

---

.asf.yaml

follow up https://github.com/apache/incubator-hugegraph-ai/pull/182

chore: add collaborators in asf config
