- src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
- src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
- src/main/java/com/baidu/hugegraph/loader/executor/LoadSummary.java
- src/main/java/com/baidu/hugegraph/loader/parser/EdgeParser.java
- src/main/java/com/baidu/hugegraph/loader/parser/ElementParser.java
- src/main/java/com/baidu/hugegraph/loader/parser/VertexParser.java
- src/main/java/com/baidu/hugegraph/loader/task/EdgeInsertionTask.java
- src/main/java/com/baidu/hugegraph/loader/task/InsertionTask.java
- src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java
- src/main/java/com/baidu/hugegraph/loader/task/VertexInsertionTask.java
- src/main/java/com/baidu/hugegraph/loader/util/HugeClientWrapper.java
- src/main/java/com/baidu/hugegraph/loader/util/LoaderUtil.java
1. When a single insert task times out, it may still cause statistical errors.
2. TashManager.shutdown() ignored singleExecutor
Fix #11 
Change-Id: I9a468241f369f4c7e73a95ba9a5772dac90e0ce1
> Fix two bug about single tasks and executor

- .gitignore
- src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
- src/test/java/com/baidu/hugegraph/loader/test/functional/LoaderTest.java
- src/test/resources/schema_date.groovy
- src/test/resources/struct_edge_use_text.json
Although unit-test under normal case can pass,  there still have some problems:
1. Collections do not support date formats.
2. In some data formats, the internal order of the collection will change.. (like list<date>)
3. It's better to add a field in `struct.json` as the list-data's start and end symbol. (optional)
4.  In theory, CSV file can support list as well, but default delimiter of CSV file is `,` ,which is conflict with the separator for collection, wonder if there is any good solution?
> support list/set when load TEXT file

- src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
- src/main/java/com/baidu/hugegraph/loader/util/JsonUtil.java
- src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
Fix parser exception cannot be caught
The reason of the problem is that the difference between new & old version of `hasNext()` & `next()`, the new version's `hasNext()` used `parse()` without exception caught.
fix #73
> Fix parser exception cannot be caught

- src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
- src/main/java/com/baidu/hugegraph/loader/reader/Line.java
- src/main/java/com/baidu/hugegraph/loader/reader/jdbc/RowFetcher.java
- src/test/java/com/baidu/hugegraph/loader/test/unit/LineTest.java
- src/test/java/com/baidu/hugegraph/loader/test/unit/UnitTestSuite.java
Change-Id: I383b3b20a162816098aa8ee8468e8255b3553fdc
> Fix line retainAll doesn't modify names and values array

- src/main/java/com/baidu/hugegraph/loader/constant/Constants.java
- src/main/java/com/baidu/hugegraph/loader/source/file/FileSource.java
- src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
- src/main/java/com/baidu/hugegraph/loader/util/DateUtil.java
- src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
- src/test/java/com/baidu/hugegraph/loader/test/unit/DateUtilTest.java
- src/test/java/com/baidu/hugegraph/loader/test/unit/UnitTestSuite.java
- src/test/resources/customized_timezone_gmt0/schema.groovy
- src/test/resources/customized_timezone_gmt0/struct.json
- src/test/resources/customized_timezone_gmt0/struct_hdfs.json
- src/test/resources/default_timezone_gmt8/schema.groovy
- src/test/resources/default_timezone_gmt8/struct.json
- src/test/resources/default_timezone_gmt8/struct_hdfs.json
Change-Id: I9814239e101e1424fc6d247a9984fcaaedbcca5c
> Support customized timezone for date

- src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
- src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
- src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
- src/main/java/com/baidu/hugegraph/loader/builder/VertexBuilder.java
Change-Id: I4fa555da0bd0ff374f9bc7107731c89c33646145
> Check non-nullable keys before insert

- checkstyle.xml
- pom.xml
- src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
- src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
- src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
- src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java
- src/main/java/com/baidu/hugegraph/loader/failure/FailLogger.java
- src/main/java/com/baidu/hugegraph/loader/mapping/ElementMapping.java
- src/main/java/com/baidu/hugegraph/loader/mapping/InputStruct.java
- src/main/java/com/baidu/hugegraph/loader/mapping/LoadMapping.java
- src/main/java/com/baidu/hugegraph/loader/progress/InputProgress.java
- src/main/java/com/baidu/hugegraph/loader/reader/file/FileLineFetcher.java
- src/main/java/com/baidu/hugegraph/loader/reader/file/OrcFileLineFetcher.java
- src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
- src/main/java/com/baidu/hugegraph/loader/reader/line/LineFetcher.java
- src/main/java/com/baidu/hugegraph/loader/serializer/InputSourceDeser.java
- src/main/java/com/baidu/hugegraph/loader/source/file/FileSource.java
- src/main/java/com/baidu/hugegraph/loader/struct/GraphStructV1.java
- src/main/java/com/baidu/hugegraph/loader/task/InsertTask.java
- src/main/java/com/baidu/hugegraph/loader/task/ParseTaskBuilder.java
- src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java
- src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
- src/main/java/com/baidu/hugegraph/loader/util/HugeClientHolder.java
- src/main/java/com/baidu/hugegraph/loader/util/MappingUtil.java
- src/test/java/com/baidu/hugegraph/loader/test/functional/JDBCLoadTest.java
- src/test/java/com/baidu/hugegraph/loader/test/unit/LoadProgressTest.java
- src/test/java/com/baidu/hugegraph/loader/test/unit/MappingConverterTest.java
Change-Id: Ieb294cbe7d9fafa4ed468b965abe61135cafd50d
> Add checkstyle plugin to check code style

- src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
- src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java
- src/main/java/com/baidu/hugegraph/loader/builder/VertexBuilder.java
- src/main/java/com/baidu/hugegraph/loader/parser/JsonLineParser.java
- src/main/java/com/baidu/hugegraph/loader/parser/TextLineParser.java
- src/main/java/com/baidu/hugegraph/loader/reader/file/ParquetFileLineFetcher.java
- src/main/java/com/baidu/hugegraph/loader/reader/hdfs/HDFSFileReader.java
- src/main/java/com/baidu/hugegraph/loader/reader/line/Line.java
- src/main/java/com/baidu/hugegraph/loader/source/AbstractSource.java
- src/main/java/com/baidu/hugegraph/loader/task/ParseTaskBuilder.java
- src/test/java/com/baidu/hugegraph/loader/test/unit/LineTest.java
Change-Id: I681255011c76067cef465f4687c0092dd08d2102
> Use array to optimize access perf in parse stage

- assembly/travis/install-hadoop.sh
- pom.xml
- src/main/java/com/baidu/hugegraph/loader/source/AbstractSource.java
- src/main/java/com/baidu/hugegraph/loader/util/DataTypeUtil.java
- src/main/java/com/baidu/hugegraph/loader/util/DateUtil.java
- src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
- src/test/resources/header_is_empty/schema.groovy
- src/test/resources/header_is_empty/struct.json
- src/test/resources/header_is_empty/struct_hdfs.json
Change-Id: Iab8011d2235d29a79ad65d4cc380d801d08896ac
> Check header not empty when user customized it

- src/main/java/com/baidu/hugegraph/loader/constant/Constants.java
- src/main/java/com/baidu/hugegraph/loader/util/HugeClientHolder.java
- src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java
- src/test/java/com/baidu/hugegraph/loader/test/functional/LoadTest.java
Change-Id: I474b8317582c5884fb2e92e14127bf123e1e4afe
> Improve some params in config and test

- src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
- src/main/java/com/baidu/hugegraph/loader/metrics/LoadSummary.java
- src/main/java/com/baidu/hugegraph/loader/metrics/RangesTimer.java
- src/main/java/com/baidu/hugegraph/loader/util/Printer.java
Change-Id: Ifb7eccde1f54ca1cf63f578db2b8e8d1a0736a73
> Fix rate inaccurate when print progress

- src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java
- src/main/java/com/baidu/hugegraph/loader/metrics/LoadSummary.java
Change-Id: I79e0c2a2d3e232cd2a5adb945214cbe3cbfe3b43
> Fix npe because missing edge mapping struct

- src/main/java/com/baidu/hugegraph/loader/builder/EdgeBuilder.java
fix [#209](https://github.com/hugegraph/hugegraph-loader/issues/209)
> fix: prase edge error when data props num is different

- README.md
- pom.xml
> skip javadoc check

- README.md
- hugegraph-client/README.md
- hugegraph-hubble/README.md
- hugegraph-loader/README.md
- hugegraph-tools/README.md
after merge to apache, we need do
> doc: add README for toolchain

- hugegraph-client/pom.xml
- hugegraph-hubble/hubble-be/pom.xml
- hugegraph-hubble/hubble-dist/pom.xml
- hugegraph-hubble/pom.xml
- hugegraph-tools/pom.xml
- pom.xml
Done:
TODO: improve the pom should be careful, it may cause a string of problems:)
> refact: init toolchain pom for all modules

- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/reader/jdbc/JDBCReader.java
- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/reader/jdbc/RowFetcher.java
- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/source/jdbc/JDBCSource.java
> feat: support use sql to construct graph for loader

- hugegraph-client/src/main/java/com/baidu/hugegraph/api/graphs/GraphsAPI.java
refer to https://github.com/apache/incubator-hugegraph/pull/1888
> chore: replace APPLICATION_JSON with TEXT_PLAIN

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/question_ask.yml
> chore: Update issue template

- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/spark/HugeGraphSparkLoader.java
> feat: support jdbc source for spark-loader

- hugegraph-hubble/hubble-fe/src/components/graph-management/NewGraphConfig.tsx
fix the placeholder of the `port input` form, as it was use the wrong description of `host`.
> fix `port input` placeholder bug

- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/flink/HugeGraphOutputFormat.java
- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/mapping/ElementMapping.java
- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/spark/HugeGraphSparkLoader.java
- hugegraph-loader/src/test/java/com/baidu/hugegraph/loader/test/unit/MappingConverterTest.java
The option `batch.max_vertices_per_batch` default value is 500, if spark/flink default value of `batch_size` is bigger than 500 ,will cause the below exception.
``` shell
class java.lang.IllegalArgumentException: Too many vertices for one time post, the maximum number is '500'
at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47)
at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93)
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:231)
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:211)
at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:58)
at com.baidu.hugegraph.driver.GraphManager.addVertices(GraphManager.java:96)
at …
```
> fix: too many vertices for one time post in spark-loader

- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/spark/HugeGraphSparkLoader.java
> fix: spark row split by delimiter failed

- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/reader/file/OrcFileLineFetcher.java
fixed: #319
Co-authored-by: ss <50285938+ssisme2019@users.noreply.github.com>
Change-Id: I13a0d663adead9b7ee66af62238c6769350ebdff
> fix: orc data import npe

- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/builder/SchemaCache.java
- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/flink/HugeGraphOutputFormat.java
- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/spark/HugeGraphSparkLoader.java
SchemaCache init and after query schema then put the latest schema to SchemaCache
I have read the CLA Document and I hereby sign the CLA
> fix: schema not cached in spark/flink loader

- hugegraph-dist/pom.xml
- hugegraph-hubble/pom.xml
Avoid creating too many temporary files by `cp` and add `maven-clean-plugin` for hubble to clean package files.
> Add maven-clean-plugin for hubble

- hugegraph-loader/src/main/java/com/baidu/hugegraph/loader/reader/line/Line.java
- hugegraph-loader/src/test/java/com/baidu/hugegraph/loader/test/unit/LineTest.java
fix line cheack argument, then it'll show detail info
> refact: show detail info when parse line meet error

- hugegraph-dist/pom.xml
```
${project.parent.basedir}: bad substitution
```
refer to https://github.com/apache/incubator-hugegraph-toolchain/pull/339#issuecomment-1296676770
> chore: fix hugegraph-dist package failed

- hugegraph-client/src/test/java/com/baidu/hugegraph/api/EdgeLabelApiTest.java
- hugegraph-client/src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
- hugegraph-client/src/test/java/com/baidu/hugegraph/api/PropertyKeyApiTest.java
- hugegraph-client/src/test/java/com/baidu/hugegraph/api/VertexLabelApiTest.java
- hugegraph-client/src/test/java/com/baidu/hugegraph/functional/EdgeLabelTest.java
- hugegraph-client/src/test/java/com/baidu/hugegraph/functional/IndexLabelTest.java
- hugegraph-client/src/test/java/com/baidu/hugegraph/functional/PropertyKeyTest.java
- hugegraph-client/src/test/java/com/baidu/hugegraph/functional/VertexLabelTest.java
- hugegraph-client/src/test/java/com/baidu/hugegraph/testutil/Utils.java
refer to https://github.com/apache/incubator-hugegraph-toolchain/actions/runs/3383405590/jobs/5619268055
```
Error:  Tests run: 100, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 207.147 s <<< FAILURE! - in com.baidu.hugegraph.functional.FuncTestSuite
Error:  testAddVertexLabelWithUserData(com.baidu.hugegraph.functional.VertexLabelTest)  Time elapsed: 0.539 s  <<< FAILURE!
java.lang.AssertionError
at com.baidu.hugegraph.functional.VertexLabelTest.testAddVertexLabelWithUserData(VertexLabelTest.java:60)
Error:  testAddEdgeLabelWithUserData(com.baidu.hugegraph.functional.EdgeLabelTest)  Time elapsed: 2.563 s  <<< FAILURE!
java.lang.AssertionError
at com.baidu.hugegraph.functional.EdgeLabelTest.testAddEdgeLabelWithUserData(EdgeLabelTest.java:97)
```
> chore: improve hugegraph-client ut & stabilize hugegraph-client-ci

- .asf.yaml
- .github/workflows/release.yml
This PR should merge as soon as possible (to avoid sending error mail by apache)
> chore: fix the missing mail address

- hugegraph-loader/src/main/java/org/apache/hugegraph/loader/HugeGraphLoader.java
- hugegraph-loader/src/main/java/org/apache/hugegraph/loader/mapping/LoadMapping.java
- hugegraph-loader/src/test/java/org/apache/hugegraph/loader/test/functional/FileLoadTest.java
- hugegraph-loader/src/test/resources/mapping_v2/schema.groovy
- hugegraph-loader/src/test/resources/mapping_v2/struct.json
Fixes: #373
```java
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/zc/IdeaProjects/incubator-hugegraph-toolchain/hugegraph-loader/hugegraph-loader-1.0.0/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/zc/IdeaProjects/incubator-hugegraph-toolchain/hugegraph-loader/hugegraph-loader-1.0.0/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Failed to start loading, cause: Failed to deserialize json
Exception in thread "main" org.apache.hugegraph.rest.SerializeException: Failed to deserialize json
at …
```
> [fix][loader] Fix deserialize json error

- hugegraph-dist/pom.xml
- hugegraph-hubble/hubble-dist/assembly/travis/install-hugegraph-hubble.sh
- hugegraph-hubble/hubble-dist/pom.xml
> fix(dist): unify binary name for hubble

- hugegraph-client/src/test/java/org/apache/hugegraph/unit/IndexLabelTest.java
IndexLabelTest has the following tests that are flaky, detected using the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool:
org.apache.hugegraph.unit.IndexLabelTest#testIndexLabel
org.apache.hugegraph.unit.IndexLabelTest#testIndexLabelV49
org.apache.hugegraph.unit.IndexLabelTest#testIndexLabelV56
The tests fail due to non-deterministic ordering of the properties in the JSON string created by the `JsonUtil.toJson()` method.
mvn -pl hugegraph-client edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.hugegraph.unit.IndexLabelTest
```
[ERROR]   IndexLabelTest.testIndexLabel:47 expected:<...ame":"personByAge","[id":0,"check_exist":true,"user_data":{},"base_type":"VERTEX_LABEL","base_value":"person","index_type":"SECONDARY","fields":["age"],"rebuild":true]}> but …
```
> Fix flaky tests in IndexLabelTest due to non deterministic JSON key ordering

- hugegraph-loader/assembly/static/bin/hugegraph-spark-loader.sh
> fix(loader): wrong shell symbol in spark script

- README.md
> chore: update README to get the maven info

- hugegraph-dist/scripts/dependency/known-dependencies.txt
- hugegraph-loader/pom.xml
> chore: keep hadoop-hdfs-client and hadoop-common version consistent

- hugegraph-loader/assembly/static/bin/hugegraph-spark-loader.sh
fix #460
I have read the CLA Document and I hereby sign the CLA
> fix: hugegraph-spark-loader shell string length limit

- .github/workflows/codeql-analysis.yml
same with server https://github.com/apache/incubator-hugegraph/pull/2308
fix: base-ref/head-ref miss in dependency-review on pushing to master
When pushing to the master branch, base-ref/head-ref isn't auto-assigned, leading to frequent errors.  The reason for omitting it is that during PRs, we can directly check for unauthorized third-party libraries using 'Dependency Review' and decide whether to include them. There's no need to showcase this during master branch pushes.
[Doc link 👇](https://github.com/actions/dependency-review-action#:~:text=base%2Dref/,none)
- xxx
- close #xxx  
- xxx
> fix: base-ref/head-ref missed in dependency-review on master

- hugegraph-hubble/hubble-dist/pom.xml
yarn may frequently cause network connection on `linux/arm64` arch
```
#22 374.1 main:
#22 379.0      [exec] yarn install v1.22.19
#22 381.2      [exec] [1/4] Resolving packages...
#22 391.1      [exec] [2/4] Fetching packages...
#22 431.2      [exec] info There appears to be trouble with your network connection. Retrying...
#22 459.7      [exec] info There appears to be trouble with your network connection. Retrying...
#22 493.0      [exec] info There appears to be trouble with your network connection. Retrying...
#22 526.6      [exec] info There appears to be trouble with your network connection. Retrying...
#22 560.0      [exec] info There appears to be trouble with your network connection. Retrying...
```
refer to https://github.com/hugegraph/actions/actions/runs/6194003062/job/1681766 …
> fix yarn network connection on linux/arm64 arch

- README.md
- hugegraph-hubble/README.md
- update the way to quick start `server` with `hubble`
- update the way to quick start `server` with `hubble`
- xxx
> doc(hubble): add docker-compose to start with server

- .github/configs/settings.xml
- .github/workflows/client-ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/hubble-ci.yml
- .github/workflows/license-checker.yml
- .github/workflows/loader-ci.yml
- .github/workflows/spark-connector-ci.yml
- .github/workflows/tools-ci.yml
- pom.xml
- When commons dependency update, we need to temporarily use the stage repository
subtask of https://github.com/apache/incubator-hugegraph-commons/pull/133
- xxx
> chore(ci): add stage profile settings

- .github/workflows/client-ci.yml
- hugegraph-client/assembly/travis/install-hugegraph-from-source.sh
- hugegraph-client/src/main/java/org/apache/hugegraph/driver/HugeClient.java
- hugegraph-hubble/Dockerfile
- hugegraph-hubble/hubble-dist/assembly/travis/download-hugegraph.sh
- hugegraph-loader/assembly/travis/install-hugegraph-from-source.sh
- hugegraph-tools/assembly/travis/install-hugegraph-from-source.sh
- close #545 
1. The right range of api version is set to 0.81 (0.71+10)
2. Build client in dockerfile instead of using client:1.0.0
tested by this yaml, where dandelionivy/hubble is my own repo
```yaml
version: '3'
services:
server:
image: hugegraph/hugegraph
#image: dandelionivy/server
container_name: graph
ports:
- 18081:8080
hubble:
#image: hugegraph/hubble
image: dandelionivy/hubble
container_name: hubble
ports:
- 8088:8088
```
now we can connect to the graph:
- xxx
> chore(client): increase the api num as the latest server commit + 10

- .github/workflows/hubble-ci.yml
- hugegraph-dist/release-docs/licenses/LICENSE-frontend-maven-plugin.txt
- hugegraph-dist/scripts/dependency/known-dependencies.txt
- hugegraph-hubble/hubble-dist/pom.xml
- hugegraph-hubble/hubble-fe/package.json
- close [#391 ](https://github.com/apache/incubator-hugegraph-toolchain/issues/513)
Introduce https://github.com/eirslett/frontend-maven-plugin to install node and yarn automatically when build.
After PR: https://github.com/apache/incubator-hugegraph-toolchain/pull/542 merged and env prepared, this pr could continue.
- xxx
> fix(hubble): build with node and yarn

- hugegraph-loader/src/main/java/org/apache/hugegraph/loader/direct/loader/HBaseDirectLoader.java
- hugegraph-loader/src/main/java/org/apache/hugegraph/loader/executor/LoadOptions.java
> fix(loader): loader options

- .github/workflows/codeql-analysis.yml
- hugegraph-client/src/main/java/org/apache/hugegraph/client/RestClient.java
- hugegraph-loader/src/main/java/org/apache/hugegraph/loader/spark/HugeGraphSparkLoader.java
- ref: https://github.com/apache/incubator-hugegraph-toolchain/pull/516
- revert some changes in: https://github.com/apache/incubator-hugegraph-toolchain/pull/538
- xxx
> fix base ref head ref and fix checkstyle

- hugegraph-dist/scripts/dependency/known-dependencies.txt
- hugegraph-loader/pom.xml
- hugegraph-tools/pom.xml
- fix [test-error](https://github.com/hugegraph/hugegraph-test/pull/7)  
- xxx
> fix: exclude okhttp1 which has different groupID with okhttp3

- hugegraph-hubble/Dockerfile
- hugegraph-loader/Dockerfile
Github action for building docker image failed https://github.com/hugegraph/actions/actions
- In Dockerfile, we can use `mvn install $MAVEN_ARGS`
- During releasing 1.2, we should use `mvn -P stage` to use apache stage repo. But currently, the dockerfile cannot use the -P stage. Hence, I add the MAVEN_ARGS which can be passed in the following way in github action:
```
uses: docker/build-push-action@v5
with:
......
build-args: ${{ env.MVN_ARGS }}
```
The `MVN_ARGS` can be set to `MAVEN_ARGS=-P stage`
Build successfully in my own repo
https://github.com/hugegraph/actions/pull/4
https://github.com/apache/incubator-hugegraph/pull/2386
- xxx
> fix: github action build docker image failed during the release 1.2 process

- README.md
- hugegraph-hubble/README.md
- hugegraph-loader/README.md
- add ASF docker policy
- and recommend users to use the release tag instead of `latest`
- xxx
> doc: adjust docker related desc in readme

- NOTICE
- hugegraph-dist/release-docs/NOTICE
> doc: update copyright date(year) in NOTICE

- hugegraph-loader/src/main/java/org/apache/hugegraph/loader/direct/loader/HBaseDirectLoader.java
> fix: concurrency issue causing file overwrite due to identical filenames

- .gitignore
- hugegraph-hubble/hubble-dist/pom.xml
- hugegraph-hubble/hubble-fe/package.json
> refactor(hubble): enhance maven front plugin

- hugegraph-loader/src/main/java/org/apache/hugegraph/loader/reader/hdfs/HDFSFileReader.java
- hugegraph-loader/src/test/java/org/apache/hugegraph/loader/test/functional/HDFSLoadTest.java
- hugegraph-loader/src/test/resources/hdfs_file_with_prefix/core-site.xml
- hugegraph-loader/src/test/resources/hdfs_file_with_prefix/schema.groovy
- hugegraph-loader/src/test/resources/hdfs_file_with_prefix/struct_hdfs.json
- close #570  
support file name with prefix for hdfs source
- xxx
> fix(loader): support file name with prefix for hdfs source

- .github/workflows/client-ci.yml
- .github/workflows/client-go-ci.yml
- .github/workflows/hubble-ci.yml
- .github/workflows/loader-ci.yml
- .github/workflows/spark-connector-ci.yml
- .github/workflows/tools-ci.yml
- hugegraph-spark-connector/assembly/travis/install-hugegraph-from-source.sh
for the release of HugeGraph 1.3.0
> chore(ci): update profile commit id for 1.3

- hugegraph-hubble/hubble-fe/yarn.lock
> chore(hubble): update yarn.lock

- README.md
Add #contributing section and update the correct CONTRIBUTING.md URL.
- close #xxx  
- xxx
> Add Contributing Section and Update CONTRIBUTING.md Link

- hugegraph-client/src/main/java/org/apache/hugegraph/structure/constant/EdgeLabelType.java
- hugegraph-client/src/main/java/org/apache/hugegraph/structure/schema/EdgeLabel.java
related to https://github.com/apache/incubator-hugegraph/pull/2682
- xxx
> fix(client): serialize source and target label for non-father edge label

- hugegraph-hubble/hubble-be/src/main/java/org/apache/hugegraph/HugeGraphHubble.java
- hugegraph-hubble/hubble-dist/assembly/static/bin/start-hubble.sh
- hugegraph-hubble/hubble-dist/assembly/travis/download-hugegraph.sh
- hugegraph-hubble/hubble-dist/assembly/travis/install-hugegraph-hubble.sh
- hugegraph-hubble/hubble-dist/assembly/travis/install-hugegraph.sh
- hugegraph-hubble/hubble-dist/assembly/travis/run-api-test.sh
- hugegraph-hubble/hubble-dist/assembly/travis/start-hubble.sh
- fix #621 #608 #302 https://github.com/apache/incubator-hugegraph/issues/1415 
- I add the charset check at initEnv function( in launching), if charset configuration is wrong, it cannot pass the check so that the hubble will throw exception when launching.
> fix(hubble): encode/decode Chinese error after building package

- hugegraph-hubble/Dockerfile
- hugegraph-hubble/hubble-dist/pom.xml
- close #xxx  
- By CI testing in https://github.com/hugegraph/actions
> fix(hubble): configure ipv4 to fix timeout of yarn install 

- .github/workflows/client-ci.yml
- .github/workflows/client-go-ci.yml
- .github/workflows/hubble-ci.yml
- .github/workflows/loader-ci.yml
- .github/workflows/spark-connector-ci.yml
- .github/workflows/tools-ci.yml
> chore(ci): update hugegraph source commit id

- .editorconfig
- .github/outdated/release.yml
- .github/workflows/client-go-ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/hubble-ci.yml
- .github/workflows/license-checker.yml
- .github/workflows/loader-ci.yml
- .github/workflows/spark-connector-ci.yml
- .github/workflows/tools-ci.yml
- hugegraph-hubble/hubble-dist/assembly/travis/requirements.txt
- hugegraph-loader/src/main/java/org/apache/hugegraph/loader/util/DataTypeUtil.java
- hugegraph-loader/src/test/java/org/apache/hugegraph/loader/test/functional/DBUtil.java
- hugegraph-loader/src/test/java/org/apache/hugegraph/loader/test/functional/JDBCLoadTest.java
- hugegraph-loader/src/test/resources/jdbc_sql_date_convert/schema.groovy
- hugegraph-loader/src/test/resources/jdbc_sql_date_convert/struct.json
add jdbc date type support include DATE、TIME、 DATETIME、 TIMESTAMP and YEAR
- fix [#298](https://github.com/apache/incubator-hugegraph-toolchain/issues/298 
- Add a test ,which show all different type import by jdbc
- I change the logic of if value is date,KafkaSource can't instaceof FileSource,So I turned them into juxtaposition logic,and add JDBC source convert
- In mysql cases,there are many type of date,and if just type casting，the error gonna happend,so I need new var to solve this problem
- testJdbcSqlDateConvert
> feat(loader): support jdbc date type & sync .editorconfig
